### ISSUE TITLE
Outstanding issues

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-reactive#11]
- [x] patching did not update the list
- [x] limiting only works with pagination
- [ ] paginated metadata should be updated
- [ ] re-fetch when list size < $limit value (on the client)
- [ ] caching
- [x] Make Rx an option (no hard dependency)
- [ ] investigate replaying events (time travel)

**Comment by AdamCanady** [comment]
Is there an ETA on when this will be ready?

**Comment by daffl** [comment]
You can use it already. The list items not checked off can be solved by using the `always` strategy when needed.

**Comment by daffl** [comment]
From using it so far I found it fairly solid so we can track individual issue separately.

For this one I have only one follow-up: https://github.com/feathersjs/feathers-reactive/issues/24
