### ISSUE TITLE
React example missing componentWillUnmount

### ISSUE THREAD

**Issue by mrpatiwi** [feathersjs/feathers-reactive#14]
Not unsubscribing can lead to setting the state of a unmounted component.

I think this should be changed to:
```js
componentDidMount() {
  this.observer = todos.find().subscribe(todos => this.setState({ todos }));
},

componentWillUnmount() {
  this.observer.unsubscribe();
},
```

**Comment by daffl** [comment]
I was wondering if this would leak. How is this normally done with React and RxJS? Are there specific components that play nice with RxJS?

**Comment by mrpatiwi** [comment]
I haven't seen anything with React + RxJS before. When using timers, it's usually done with mixins, but it's easier with: https://github.com/reactjs/react-timer-mixin/issues/4#issuecomment-149999442

**Comment by daffl** [comment]
It would be nice to have a component where you can call something like `setState({ todos: todoService.find() })` and it will subscribe and unsubscribe automatically.

I also added the change you suggested. Thanks!

**Comment by ekryski** [comment]
@daffl the common pattern is to be explicit about unregistering your event listener inside `componentWillUnmount`. Using mixins has become a bit of an anti-pattern because it's not immediately apparent what the mixin does.

**Comment by daffl** [comment]
That's fine, I guess all I'd be looking for is a helper that turns a state object into an observable. E.g.

```js
componentDidMount() {
  const state = Rx.Observable.from({
    todos: app.service('todos').find(),
    user: app.service('users').get(0),
    text: ''
  });

  this.state = state.subscribe(this.setState);
},

componentWillUnmount() {
  this.state.unsubscribe();
}
```
