### ISSUE TITLE
Problems with React Native

### ISSUE THREAD

**Issue by mrpatiwi** [feathersjs/feathers-reactive#16]
I'm having this error while running this plugin with a React Native app (Android emulator or device):
<img width="526" alt="captura de pantalla 2016-05-28 a las 16 37 14" src="https://cloud.githubusercontent.com/assets/7570744/15629572/71bcc36e-24f2-11e6-82cb-194bb1719bb3.png">

```js
omit: function omit(obj) {
    var result = _extends({}, obj);

    for (var _len = arguments.length, keys = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      keys[_key - 1] = arguments[_key];
    }

    var _iteratorNormalCompletion = true;
    var _didIteratorError = false;
    var _iteratorError = undefined;

    try {
      // Here
      for (var _iterator = keys[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
        var key = _step.value;

        delete result[key];
      }
    } catch (err) {
      // ...
```

Original `utils.js` file comes from `feathers-commons`: https://github.com/feathersjs/feathers-commons/blob/master/src/utils.js#L27

Running in the iOS emulator works great, but it seems to not work on a real device.

I made a project to show the error (also tried older versions of RN and Rxjs).
https://github.com/mrpatiwi/reactNativeRxjs

**Comment by mrpatiwi** [comment]
Using a forEach loop instead of a `(let key of keys)` fix the Symbol error, but it produces a Time Out exception now.

```js
keys.forEach(key => delete result[key]);
```

![image](https://cloud.githubusercontent.com/assets/7570744/15629762/f32c5932-24f7-11e6-916e-cdd7bb42982e.png)

`client.js` belongs to `feathers-socket-commons`, `send` method.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/feathers-commons/pull/25 in v0.7.4.

I'm not sure how much of ES6 React Native JS engines support but this problem might also be fixed by including [babel-polyfill](https://www.npmjs.com/package/babel-polyfill) (which is probably generally not a bad idea to include).

Thanks a lot for the fix!

**Comment by ekryski** [comment]
Yeah I think that was an issue with your babel config. RN needs some specific set ups.
