### ISSUE TITLE
Merge doesn't work?

### ISSUE THREAD

**Issue by ryuken** [feathersjs/feathers-reactive#19]
Hi I tried the merge option on all levels (application, service and method), but it is never triggered.

```js
.configure(rx(RxJS, {
        merge : function(current, data) {
            console.log(current, data);
        }
    }))
```

```js
const userService = app.service('users').rx({ merge : function(current, data) {
    console.log(current, data);
}})
```

```js
userService
    .find({
        merge : function(current, data) {
            console.log(current, data);
        }
}).subscribe(users => dispatch(receive_users(users.data))
```

Am I doing something wrong?

**Comment by harangue** [comment]
Hey @ryuken! You can see the place where `options.merge` is used in [this file](https://github.com/feathersjs/feathers-reactive/blob/d205ad60f01ab7930c0c01ca50377b65ee49ee3c/src/resource.js) - it will only be applied on an `update` `patch` or `create`. Are you sure one of those events is being broadcasted?

**Comment by daffl** [comment]
I think it will only work for `update`, `patch`, `remove` and `created`. `find` does not use `merge` at the moment, the updated or patched item will just be replaced (in https://github.com/feathersjs/feathers-reactive/blob/master/src/strategies.js#L54).

**Comment by ryuken** [comment]
I know that it only works on update, patch, remove and created.
But if you subscribe on find you will also get updates from those actions.
When I subscribe on find and execute a patch I will get only the patched data (which will replace the whole array which I don't want)
Or am I using this incorrectly?

**Comment by daffl** [comment]
What I meant was that `find` does not use `merge`. Only the `update`, `patch`, `remove` and `create` methods that return a single resource do. When calling `find` updated and patched resources just get replaced with the event data. As you pointed out it definitely should use `merge` there as well. I should have a fix shortly.

**Comment by ryuken** [comment]
Ah great I understand it thanks again

**Comment by daffl** [comment]
Sorry, this took a while but I decided to remove the `merge` option in the latest version 0.3.0. By default Feathers dispatches the events in a way that the data can just be replaced so I don't think it is really necessary. If it is for some reason we can circle back and add an option to customize the event and method streams.
