### ISSUE TITLE
find() shouldn't be executed before subscribing

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers-reactive#20]
Since the Observable is generated `fromPromise`, its logic is executed on creation rather than on subscription.

Thus automatic retries or automatic subscription after auth are cumbersome at best.

I'm not familiar with how feathers' plugin system works, so please bear with me. I managed to hack feathers-reactive to return a cold observable when `find()` is called. ~~However I didn't really dive into how the listStrategy works. Reactivity seems to be broken.~~

Unfortunately, this approach breaks "promisification". Is there anything to it besides backward compatibility?

list.js now basically looks like this:
```
export default function(Rx, events, options) {
  return function (params = {}) {
    const query = Object.assign({}, params.query);

    const __super = this._super;

    const obs = Rx.Observable.create(observer => {
      const _observer = observer;

      __super.apply(this, arguments)
        .then(res => {
          _observer.next(res);
          _observer.complete();
        })
        .catch(e => _observer.error(e));
    });

    // Hack because feathers-query-params deletes stuff from `params.query`
    // Will be fixed in the next version
    params.query = query;

    options = Object.assign(options, this._rx, params.rx);

    return options.listStrategy.call(this, obs, events, options, args);
}
```

This enables me to do stuff like this:

```
authed$:Subject<boolean> = new Subject<boolean>();

this.feathers.service('items')
      .find()
      .delayWhen(
        () => Observable.of(0), // no emission delay
        this.authed$ // delay subscription until this.authed$ emits true
      )
      .subscribe(res => console.log(res));
```

Not authenticated, yet? Doesn't matter:

```
feathers.authenticate({
      type      : 'local',
      'email'   : email,
      'password': password
    })
      .then(() => this.authed$.next(true))
      .catch(error => console.error('Error authenticating!', error));
```

**Comment by harangue** [comment]
Thanks for sharing this!

I don't know about you @daffl, but I'd be inclined to make this an optional configuration. Promises are pretty fundamental to the workings of Feathers and it'd be dangerous to break that expectation.

**Comment by daffl** [comment]
I agree, that makes sense. We can still [promisify](https://github.com/feathersjs/feathers-reactive/blob/master/src/utils.js#L4) the returned Observable (which is what is done currently) but it seems like this behaviour is better.

@j2L4e Could you add a test for your usecase?

**Comment by j2L4e** [comment]
No problem. Will do as soon as I find the time.

**Comment by j2L4e** [comment]
Here you go.

```
    it('queries on subscription rather than creation', done => {
      let trigger$ = new Rx.Subject();

      let result;

      service.find()
        .delayWhen(() => Rx.Observable.of(0), trigger$) // delay subscription until trigger$ emits
        .subscribe(messages => {
          result = messages;
          assert.deepEqual(messages, [ { text: 'A test message', [id]: 0 } ]);

          done();
        });

      setTimeout(() => {
        assert.equal(result, undefined);
        trigger$.next(null);
      }, 20);
    });
```

**Comment by daffl** [comment]
@j2L4e Thanks. I'm confused though. Where is that commit located?

**Comment by j2L4e** [comment]
Weird. I have no idea why it seems to be in your repo. You can find it here in my fork https://github.com/j2L4e/feathers-reactive/tree/j2l4e-dev

**Comment by daffl** [comment]
Ah sweet, that makes sense. Would you mind making a pull request so that we can release a new version?

**Comment by daffl** [comment]
Closed via #21

**Comment by daffl** [comment]
So for #31 I added this for `get` as well in #32 but it doesn't seem to work right and I am not sure why.

I'm also not sure we can do this for the other methods (`create`, `remove`, `update` and `patch`) since you should still be able to do fire-and-forget things like `service.create(data)` without having to explicitly subscribe. Unfortunately that means something like:

```js
this.feathers.service('items')
      .create(data)
      .delayWhen(
        () => Observable.of(0), // no emission delay
        this.authed$ // delay subscription until this.authed$ emits true
      )
```

Won't be possible. Can anybody think of other options?

**Comment by daffl** [comment]
My suggestion would be to revert the change for `find` (although I really don't want to but it is kind of weird if that one methods works differently than all the others) and adding a `createSource` callback in the options where you could implement the delayed subscription logic yourself and it just uses `fromPromise` by default.

**Comment by j2L4e** [comment]
You're right, it's weird. However, I can't really think of why you would want to delay upserts or why you would need to subscribe to them over time. As we're in reactive-land anyway, one would imho have subscribed to a `get` or `find` before upserting. 

The way `find` and `get` worked before #21 was weird as well, because it is not a behavior someone who's dealing with rxjs a lot would expect.

**Comment by daffl** [comment]
I don't think Promise compatibility is the problem. As far as I know, all Observables can be converted to a Promise at any time. The current wrapper is just a more convenient way for doing `stream.take(1).toPromise()` all the time and happens to keep the service return values backwards compatible.

What I was saying is that if we do this change all the way, _all_ methods would delay until someone subscribes to the Observable which makes this plugin much more cumbersome to use with e.g. React. You'd have to do `service.create(data).subscribe(() => {})` instead of a plain `service.create(data)` to get the method to run at all. I guess Angular does the subscription automatically.

My suggestion is to make the creation of a stream configurable. The default and with the old behaviour it would look like this:

```js
app.configure(rx(RxJS, {
  createStream(method, args) {
    return RxJS.Observable.from(method(... args));
  }
}));
```

To get the behaviour of running the method on subscription you would then configure it with:

```js
app.configure(rx(RxJS, {
  createStream(method, args) {
    let result = null;

    return Rx.Observable.create(observer => {
      const _observer = observer;

      if(!result) {
        result = method(... args)
      }

      result.then(res => {
        _observer.next(res);
        _observer.complete();
      })
      .catch(e => _observer.error(e));
    });
  }
}));
```

**Comment by j2L4e** [comment]
Off the top of my head I can't come up with anything better than your solution.
I find a boolean for configuration to be enough, though.

```
app.configure(rx(RxJS, {
  lazy: false //default
}
```

```
find(...){
  return (lazy) ? Rx.Observable.create(...) : Rx.Observable.fromPromise(...);
}
```


Depending on `lazy`

**Comment by daffl** [comment]
Thanks for the feedback and good call for the `lazy` option. I implemented it in https://github.com/feathersjs/feathers-reactive/pull/34 and will release it as v0.4.0
