### ISSUE TITLE
listStrategy doesn't work as mentioned in readme

### ISSUE THREAD

**Issue by danielang** [feathersjs/feathers-reactive#26]
I'm very new to feathers and RxJS so... my mind is blown :P
But...
```js
app.service('serviceName').rx({
    idField: '_id',
    listStrategy: 'always'
});
```
does not work. I figured out, that I must pass this expression: `feathers.rx.strategy(Rx).always` to `listStrategy`. Then it works as expected.

By the way
```js
// Always fetch fresh data for this method call
app.service('todos').find({ listStrategy: 'always' });
```
should be
```js
// Always fetch fresh data for this method call
app.service('todos').find({rx: { listStrategy: 'always' }});
```
Correct?

**Comment by daffl** [comment]
You are correct. Would you mind making a PR with that change?

Also, it looks like `listStrategy` as a string only gets converted at the top level configuration (in https://github.com/feathersjs/feathers-reactive/blob/master/src/index.js#L29). I should have a fix for it shortly.
