### ISSUE TITLE
requests performed multiple times

### ISSUE THREAD

**Issue by j2L4e** [feathersjs/feathers-reactive#29]
Related to #20. 

Queries are now sent to the server at least twice. It's seems to happen due to the listStrategy subscribing multiple times.

I'm afraid I don't get how feathers' plugin system actually works. 
I have no clue, what `this` and `_super` in list.js actually refer to.
So I wasn't able to get to the bottom of this at all.

**Comment by daffl** [comment]
`this` is the service and `_super` the original service method that is being overwritten (provided by [Uberproto](https://github.com/daffl/uberproto)).

This might be a lot easier to track down with some breaking code.

**Comment by j2L4e** [comment]
I see. I have almost exclusively been working with TypeScript, so es5 inheritance is kind of a mystery to me and feels really hacky.
I'll have a look when i find the time.

**Comment by daffl** [comment]
Well this is more of a mixin, not inheritance and I don't think Typescript has finalized a mixin mechanism yet either right? Either way, just a small breaking example would help a lot to figure out what's happening.

**Comment by timelesshaze** [comment]
Hello!
This is a test case that makes the same query at least twice (it always stays between 2-3 queries).
Although this code is mostly vanilla ES6, it is transpiled with TS.

```typescript
import * as io from 'socket.io-client';
const feathers = require('feathers-client');
const feathersReactive = require('feathers-reactive');

const socket = io('http://localhost:3030/');
const app = feathers()
  .configure(feathersReactive(RxJs))
  .configure(feathers.socketio(socket));

app.service('customers').find().subscribe((customers) => console.log('Customers', customers));
```

**Comment by daffl** [comment]
Thank you, I'll write a test for it. I'm suspecting the issue to be somewhere around https://github.com/feathersjs/feathers-reactive/blob/master/src/list.js#L29. `toPromise` should probably only be called once `.then` or `.catch` is being called.
