### ISSUE TITLE
previous data lost when patch/remove with listStrategy='smart'

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-reactive#37]
I am not sure if I used it in a wrong way or this behavior is intentional: 

```js
app = feathers()
.configure(socketio(io('....'))
.configure(reactive(RxJS, {listStrategy: 'smart'}))

cards = app.service('cards')
cards.find().subscribe(data => console.log('a: ', data))

window.test= => cards.patch('xxx', {text:"new"})
```

Before running `test()`, the console shows an array of 10 items fetched from database; but after `test()` it has only one item left, that is the one been patched. The console looks like:

```
a: [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object]
run()
a: [Object]
```

Same problem with `update` and `remove`. `create` is OK.

Is this a bug or I misunderstood what this package is for?

**Comment by daffl** [comment]
It's probably because of `idField` not configure properly (which is set to `id` by default). 

```js
app.configure(reactive(RxJS, {listStrategy: 'smart', idField: '_id' }))
```

Should do it. I'll probably change and make it mandatory.

**Comment by beeplin** [comment]
yes, now it works with idField configured.

**Comment by daffl** [comment]
I'll reopen this as a reminder to make `idField` mandatory.

**Comment by hubgit** [comment]
I just hit this problem (the result list became empty after removing an item), and setting `idField` fixed it.

I don't suppose Feathers can get the information about the `id` field from the server somehow, where it's already been configured?

**Comment by daffl** [comment]
Not really without adding service introspection which is not trivial to secure properly. I'm still making the change to have the id field being mandatory and potentially throwing an error if an item does not have the id field.

**Comment by dottodot** [comment]
I'm experiencing a similar issue but only if I alter the original query. 

For example I have a list of items with a published / unpublished status so on first load it shows all published items. If at this point if I mark an item as unpublished the list correctly updates. However if I update the list to say display unpublished items then try to update an item to published I get the behaviour described above where the data is lost.

This is my initial subscription, where the query is a BehaviourSubject
```
  getItems() {
    this.serviceSub = this.query.mergeMap(query => this.mainService.find({ query: query }));
    this.serviceSub.subscribe(resp => {
      this.total = resp.total;
      this.items = resp.data;
      this.isLoading = false;
    });
  }
```
This itself works fine in terms of updating the results but any patch updates afterwards fail.

This is what my patch request looks like

```
  unpublish(id:string, status: boolean) {
    this.mainService.patch(id, {published: status});
  }
```

**Comment by daffl** [comment]
Setting `idField` is now mandatory in v0.5.0 thanks to #58
