### ISSUE TITLE
Is there a way to update query params?

### ISSUE THREAD

**Issue by arddor** [feathersjs/feathers-reactive#39]
Is it possible to update / alter query params after subscribing? The reason why I'm asking is that I'm working on a data table and it should be possible to change sorting persistently. Currently I'm just refetching the data, however on a create or update it goes back to the original defined sorting. 

I guess the proper way is to unsubscribe and then subscribe again with the new query params?

**Comment by daffl** [comment]
I did that with RXJS directly:

```js
const service = app.service('messages');
const query = new RxJS.BehaviorSubject(props.query || {});

const find = query.mergeMap(query => service.find({ query }));

find.subscribe(data => console.log('Data is', data));

query.next({ $skip: 10 });
```

**Comment by arddor** [comment]
Awesome thank you
