### ISSUE TITLE
Impossible to type

### ISSUE THREAD

**Issue by harangue** [feathersjs/feathers-reactive#41]
I'm still slowly (but surely) working my way through and typing some core Feathers libraries. Unfortunately, I'm at an impasse with feathers-reactive. There's just no good way to statically type a function that can return both a `Promise` and an `Observable`. At best, you treat the return type as generic, but that gets messy very quickly.

While I was thinking of possible solutions, it occurred to me that the fact that this can't easily be described with a type system maybe means that it shouldn't be that way. Magically returning both a Promise and Observable with `promisify` is arguably not ideal from an API design standpoint.

I think one possible solution would be to use the existing method registered on the service output and have that be the exclusive thing that transform the return type, like:
```
service.rx().find({}).subscribe
```

Alternatively, the service method calls themselves could change, like
```
service.findReactive({})
```
though this is maybe a bit confusing to developers.

Any thoughts on this?

**Comment by daffl** [comment]
Couldn't you create a new type that extends the Observable type and has the `.then(callback)` and `.catch(callback)` methods? That's basically all it does anyway.

**Comment by harangue** [comment]
@daffl I've tried a few variations of that but it's complicated greatly by the fact that the type has to be modified on an entirely different declaration file. Extending the static types of modules with an entirely module is tricky and likely not possible in this case without an API change.

**Comment by daffl** [comment]
What if you just type it as an Observable (you can always do `.first().toPromise()`) or does TypseScript blow up if it somehow finds methods that it didn't expect?

It's also weird to me that you can't extend an existing interface. Every static language I know of can do that.

**Comment by daffl** [comment]
Fixed by @j2L4e via #58 and released as v0.5.0
