### ISSUE TITLE
Observable.throw() is not subscribable

### ISSUE THREAD

**Issue by elaijuh** [feathersjs/feathers-reactive#47]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

```
service.create(data)
  .catch(err => Observable.throw(err))
  .subscribe(x=>x, err=>err)
```

### Expected behavior
Observable.throw() should be subscribed

### Actual behavior
It throws error that subscribe is not a function of Observable.throw()

### System configuration

rxjs: 5.2.0
feathers-reactive: 0.4.1

**Comment by daffl** [comment]
Wouldn't that be a problem of the version of RxJS you are using?

**Comment by elaijuh** [comment]
But `Observable.fromPromise` works

**Comment by daffl** [comment]
This should now also be working properly in v0.5.0
