### ISSUE TITLE
Mixin of watch function into feathers service not working

### ISSUE THREAD

**Issue by RicciFlowing** [feathersjs/feathers-reactive#67]
### Steps to reproduce

`  app = feathers();    `             
 ` app.configure(feathersRx({        
      idField: '_id'
    })); `
` console.log(app.service('messages')) // No property watch() here!`

### System configuration

**Browser Version**:
Firefox Version 55 (Working on Chromium for me)

I've down some research and the problem seems to be related to the way Uberprotos implements mixin()  and the fact that FF defines Object.prototype.watch().

**Comment by j2L4e** [comment]
Awesome, thanks for the research!

This issue doesn't seem fixable upstream, so I've created a workaround for FF in #68. Confirmed working on FF 55 / Ubuntu.

**Comment by RicciFlowing** [comment]
Thanks for the quick fix.
