### ISSUE TITLE
Link to outdated docs confuses about project state

### ISSUE THREAD

**Issue by COLABORATI** [feathersjs/feathers-reactive#70]
The first sentence in the project description links to an outdated ("legacy") part of the feathers documentation - this is very confusing. Is this a part of the project that is not maintained any more? Is it not compatible with the rest of feathers code? Will it be compatible with future developments? Too many questions that arise from that single url to deprecated docs...

The whole ecosystems looks very fragmented already - it would be a great help and much easier to follow these developments if creators tried to keep the project docs consistent.

Thank you very much for your attention!

**Comment by daffl** [comment]
Indeed. The correct link is https://docs.feathersjs.com/api/events.html#service-events, a pull request would be very welcome.
