### ISSUE TITLE
feathers-reactive not responding to create event with query applied in .find() (possibly related to #62)

### ISSUE THREAD

**Issue by jobobo21** [feathersjs/feathers-reactive#73]
### Steps to reproduce

const assignjobs = empNumber => {
  const jobassign = app.service("assign");
  jobassign
    .watch({ listStrategy: "always" })
    .find({
//create event triggers without query parameters
      query: {
        empnumber: empNumber
      }
    })
    .subscribe(jobs => {
      console.log(jobs);
      store.dispatch(rtupdate(jobs, "assignedjobs"));
    });
};

### Expected behavior
On create event  the redux dispatch should trigger.
If I remove the query in find the create event triggers an update. 
### Actual behavior
Every other event in crud triggers correctly except "create".

### System configuration
/* This is in index that gets imported to the react method above
export const app = feathers()
  .configure(socketio(socket))
  .configure(reactive({ idField: "id" })); */
On the feathers side I am using sequelize as the orm.

**Module versions** (especially the part that's not working):
Feathers server is version 2.2.2
feathers-reactive on client is 0.5.3
**NodeJS version**:
v8.6.0

**Operating System**:
Ubuntu 16.04 lts
**Browser Version**:
chromium 61.0.3163

**Comment by daffl** [comment]
Does the data returned by the event match the query?

**Comment by jobobo21** [comment]
Yeah it does match the query upon reloading the app the posted result is consumed. And on delete that entry is omitted immediately. Working on a simplified demo version for clarity right now.

**Comment by jobobo21** [comment]
So I have Isolated the problem. When sending a value to query, if the value does not have the correct prop type (int, string, float, ect...), a "create" event will not be triggered with the query. What threw me off was that all the other "CRUD" events had no problem. I'm not sure if you would classify that as a bug per say. These are just my findings using feathers with sequelize as the orm.  At the end of the day makes for some very fun troubleshooting so hopefully if someone falls into the same net they will find this.

**Comment by daffl** [comment]
It's tricky because it depends on the ORM and `feathers-reactive` on the client won't know about how it converts those values. We actually had this as a fuzzy comparison in https://github.com/feathersjs/feathers-commons/blob/master/src/utils.js#L165 before but that was causing other issues.

Thanks for digging into this!
